- name: enable nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf: 
    name: nginx
    state: present

- name: remove default html content
  ansible.builtin.file:
    name: /usr/share/nginx/html/* 
    state: absent

- name: delete the frontend tar
  ansible.builtin.file:
    path: /tmp/frontend.zip
    state: absent

- name: download frontend html content
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
    dest: /tmp/{{ component }}.zip

- name: unarchieve {{ component }}
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove nginx.conf
  ansible.builtin.file:
    name: /etc/nginx/nginx.conf
    state: absent

- name: copy the nginx conf file from repo
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: start and enable nginx
